# Generated by Django 4.2.3 on 2023-07-19 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User ID',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Wallet name')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Current balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='accounting.user', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Income date')),
                ('type_of_transaction', models.CharField(choices=[('in', 'income'), ('ex', 'expanse')], max_length=60)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'Income',
            },
        ),
    ]
